name: Github Package Cleanup

on:
  schedule:
    - cron: '30 3 3 * *'
  workflow_dispatch:
    inputs:
      num-to-keep:
        description: 'Number of package versions to keep'
        required: false
        default: '5'

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'hdhr-dvr-docker'
          package-type: 'container'
          min-versions-to-keep: ${{ github.event.inputs.num-to-keep || 5 }}
