name: Github Package Cleanup

on:
  schedule:
    - cron: '30 3 3 * *'
  workflow_dispatch:
    inputs:
      num-to-keep:
        description: 'Number of package versions to keep'
        required: false
        default: '5'

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old package versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP: ${{ github.event.inputs.num-to-keep || 5 }}
        run: |
          # Fetch package versions, skip the specified number of newest versions, and delete the rest
          VERSIONS=$(gh api /user/packages/container/hdhr-dvr-docker/versions --paginate --jq ".[$KEEP:].id")
          for id in $VERSIONS; do
            echo "Deleting package version ID: $id"
            gh api --method DELETE /user/packages/container/hdhr-dvr-docker/versions/$id
          done
