name: Github Package Cleanup

on:
  schedule:
    - cron: '30 3 3 * *'
  workflow_dispatch:
    inputs:
      num-to-keep:
        description: 'Number of package versions to keep'
        required: false
        default: '5'

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old package versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP: ${{ github.event.inputs.num-to-keep || 5 }}
          OWNER: ${{ github.repository_owner }}
          REPO: HDHR-DVR-docker
        run: |
          # Fetch package versions for this specific user repository
          VERSIONS=$(gh api "/users/$OWNER/packages/container/$REPO/versions" --paginate --jq "if type == \"array\" then .[$KEEP:][].id else empty end")
          
          if [ -z "$VERSIONS" ]; then
            echo "No package versions to delete (less than or equal to $KEEP versions exist)."
          else
            for id in $VERSIONS; do
              echo "Deleting package version ID: $id"
              gh api --method DELETE "/users/$OWNER/packages/container/$REPO/versions/$id"
            done
          fi
